title: UCincy Grad Bayesian Analysis Group
description: >- # this means to ignore newlines until "baseurl:"
 Welcome to the UCincy Grad Bayesian Analysis Group! We're a team of graduate statistics students at the University of Cincinnati, deeply engaged in applying Bayesian statistics to complex, real-world data. Our weekly sessions are a blend of textbook discussions and hands-on data analysis, diving into the depths of advanced Bayesian topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
